### ISSUE TITLE
[Question] Item Quantities

### ISSUE THREAD

**Issue by ghost** [josephcsible/PistonCompression#3]
So I know this mod can create a given quantity of items, the config file states as much, but I can't seem to get it to work. If, for example, I wanted to compress purpur blocks into 16 ender pearls, what would I have to put in the config file to achieve this?

**Comment by josephcsible** [comment]
Try this:
```
minecraft:purpur_block * minecraft:ender_pearl 0 16
```
Let me know if that works for you.
