### ISSUE TITLE
[Bug] Unable to compress to blocks from other mods?

### ISSUE THREAD

**Issue by ghost** [josephcsible/PistonCompression#4]
I'm not sure exactly what the issue is, but I'm unable to compress vanilla bone blocks to Quark limestone.

The error I get is "Ignoring replacement with unknown new block or item: minecraft:bone_block * quark:limestone 0".

**Comment by josephcsible** [comment]
Version 1.1.1 contains the fix.

EDIT: Curse seems to be taking a while to approve it. If you're seeing this before it's approved, you can download it from [the GitHub releases page](https://github.com/josephcsible/PistonCompression/releases) now.
